import { useResource } from '../useResource';
import { cuttingReleasesApi } from '../../utils/api';
import { CuttingRelease } from '../../types';

const mapCuttingRelease = (raw: any): CuttingRelease => ({
  id: raw.id ?? raw.ID ?? 0,
  releaseNumber: raw.releaseNumber ?? raw.ReleaseNumber ?? '',
  cutDate: raw.cutDate ?? raw.CutDate ?? raw.releaseDate ?? raw.ReleaseDate ?? '',
  week: raw.week ?? raw.Week ?? 0,
  section: raw.section ?? raw.Section ?? '',
  group: raw.group ?? raw.Group ?? 1,
  releaseDate: raw.releaseDate ?? raw.ReleaseDate ?? '',
  fgpoId: raw.fgpoId ?? raw.FGPOId ?? 0,
  fgpoNumber: raw.fgpoNumber ?? raw.FGPONumber ?? '',
  customerName: raw.customerName ?? raw.CustomerName ?? '',
  style: raw.style ?? raw.Style ?? '',
  color: raw.color ?? raw.Color ?? '',
  fabricLot: raw.fabricLot ?? raw.FabricLot ?? '',
  fabricDescription: raw.fabricDescription ?? raw.FabricDescription ?? '',
  layers: raw.layers ?? raw.Layers ?? 0,
  piecesBySize: raw.piecesBySize ?? raw.PiecesBySize ?? {},
  total: raw.total ?? raw.Total ?? 0,
  bodyBySize: raw.bodyBySize ?? raw.BodyBySize ?? {},
  rolls: raw.rolls ?? raw.Rolls ?? 0,
  ydsPackingList: raw.ydsPackingList ?? raw.YdsPackingList ?? 0,
  physicalYards: raw.physicalYards ?? raw.PhysicalYards ?? 0,
  short: raw.short ?? raw.Short ?? 0,
  percentShort: raw.percentShort ?? raw.PercentShort ?? 0,
  fDamage: raw.fDamage ?? raw.FDamage ?? 0,
  percentDamage: raw.percentDamage ?? raw.PercentDamage ?? 0,
  overlaps: raw.overlaps ?? raw.Overlaps ?? 0,
  pcsPerMarker: raw.pcsPerMarker ?? raw.PcsPerMarker ?? 0,
  totalYds: raw.totalYds ?? raw.TotalYds ?? 0,
  markerLength: raw.markerLength ?? raw.MarkerLength ?? 0,
  markerYield: raw.markerYield ?? raw.MarkerYield ?? 0,
  realYield: raw.realYield ?? raw.RealYield ?? 0,
  width: raw.width ?? raw.Width ?? 0,
  efficiency: raw.efficiency ?? raw.Efficiency ?? 0,
  approvedCutQty: raw.approvedCutQty ?? raw.ApprovedCutQty ?? 0,
  approvedWidth: raw.approvedWidth ?? raw.ApprovedWidth ?? 0,
  markerNumber: raw.markerNumber ?? raw.MarkerNumber ?? '',
  approvedYield: raw.approvedYield ?? raw.ApprovedYield ?? 0,
  prrResult: raw.prrResult ?? raw.PrrResult ?? '',
  releasedBy: raw.releasedBy ?? raw.ReleasedBy ?? '',
  reviewedBy: raw.reviewedBy ?? raw.ReviewedBy ?? '',
  exception: raw.exception ?? raw.Exception ?? '',
  conditions: raw.conditions ?? raw.Conditions ?? '',
  releaseStatus: raw.releaseStatus ?? raw.ReleaseStatus ?? '',
  comments: raw.comments ?? raw.Comments ?? '',
  active: raw.active ?? raw.Active ?? true,
  createdAt: raw.createdAt ?? raw.CreatedAt ?? '',
  updatedAt: raw.updatedAt ?? raw.UpdatedAt,
});

/** Hook de Cutting Release: consume /api/cutting-releases */
export const useCuttingReleases = () =>
  useResource<CuttingRelease>(cuttingReleasesApi, mapCuttingRelease);
