// Cutting Release (liberación de tela aprobada para corte)

export interface CuttingRelease {
  id: number;
  releaseNumber: string;
  cutDate: string;
  week: number;
  section: string;
  group: number;
  releaseDate: string;
  fgpoId: number;
  fgpoNumber: string;
  customerName: string;
  style?: string;
  color?: string;
  fabricLot?: string;
  fabricDescription?: string;
  layers: number;
  piecesBySize?: Record<string, number>;
  total: number;
  bodyBySize?: Record<string, number>;
  rolls: number;
  ydsPackingList: number;
  physicalYards: number;
  short: number;
  percentShort: number;
  fDamage: number;
  percentDamage: number;
  overlaps: number;
  pcsPerMarker: number;
  totalYds: number;
  markerLength: number;
  markerYield: number;
  realYield: number;
  width: number;
  efficiency: number;
  approvedCutQty: number;
  approvedWidth: number;
  markerNumber?: string;
  approvedYield: number;
  prrResult?: string;
  releasedBy?: string;
  reviewedBy?: string;
  exception?: string;
  conditions?: string;
  releaseStatus?: string;
  comments?: string;
  active: boolean;
  createdAt: string;
  updatedAt?: string;
}

export interface CreateCuttingReleaseInput {
  cutDate: string;
  week: number;
  section: string;
  group: number;
  releaseDate: string;
  fgpoId: number;
  fabricLot?: string;
  fabricDescription?: string;
  layers: number;
  piecesBySize?: Record<string, number>;
  total: number;
  bodyBySize?: Record<string, number>;
  rolls: number;
  ydsPackingList: number;
  physicalYards: number;
  short: number;
  percentShort: number;
  fDamage: number;
  percentDamage: number;
  overlaps: number;
  pcsPerMarker: number;
  totalYds: number;
  markerLength: number;
  markerYield: number;
  realYield: number;
  width: number;
  efficiency: number;
  approvedCutQty: number;
  approvedWidth: number;
  markerNumber?: string;
  approvedYield: number;
  prrResult?: string;
  releasedBy?: string;
  reviewedBy?: string;
  exception?: string;
  conditions?: string;
  releaseStatus?: string;
  comments?: string;
}
